GET http://localhost:3000/blogs

####Post all

POST http://localhost:3000/blogs
Content-Type: application/json

{
    "title": "The Conjuring",
    "price": 95.00,
    "content": "Horror",
    "img": "https://i.postimg.cc/x8qMCxDs/the-conjuring.jpg"
}



#### Get by id
GET  http://localhost:3000/blogs 

### Remove blog

DELETE http://localhost:3000/blogs/6227521fb0881031b05f6c14

### Update

PATCH http://localhost:3000/blogs/6227521fb0881031b05f6c14

Content-Type: application/json

{
    "title":"amazing girl"
}